version: '3.8'

services:
  # MINIO
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio-storage-shikaku
    environment:
      MINIO_ROOT_USER: minioadminshikaku
      MINIO_ROOT_PASSWORD: minioadminshikaku
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console Web
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
